# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c4638cae11e6ca34e6751c666c72a7ad2738ea4ecbcf446d69b13b560f2ab6ea7191313e1f425fc0a1433256a05dfdd98364b24d39cfe878dbe58f4246b9cb4e

test:
  secret_key_base: 9f8c10d2eb6b393c748d02c6f7107de3ce00f2c4db507ab08fcb3016f147ee10e27577af555a2a4ef83dbb241b337ba1d9f0a42e9bbb0947c9b0a360b4a0c847

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
